# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd43ea0394904a2c829a43d2bc5e6b8349c49a9b2525388f19e86c84b5b2982d80e7db020bb81f4c813e5054e897212dc7ca553058476aba81892dd557d04c86

test:
  secret_key_base: f610a241e9b27da3c1f19751ea0c36f2a740857a17872fa9bd04c45e82546f6f9d0a21562fabaf675c100cf3b1cf42774db77f3c78f2f11cd160319e5c7a0c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
